# Generated by Django 5.0.6 on 2024-06-07 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_founded', models.IntegerField(max_length=4)),
                ('stadium', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('manager', models.CharField(max_length=30)),
                ('championships', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('pref_foot', models.CharField(max_length=5)),
                ('nationality', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=2, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(40)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
        ),
    ]
