# Generated by Django 5.0.6 on 2024-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='year_founded',
            field=models.IntegerField(),
        ),
    ]
