# Generated by Django 5.0.6 on 2024-06-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_year_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='year_founded',
            field=models.IntegerField(max_length=4),
        ),
    ]
