# Generated by Django 5.0.6 on 2024-06-07 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_year_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='championships',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='year_founded',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
