# Generated by Django 5.0.6 on 2024-06-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_player_age_alter_team_championships_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pref_foot',
            field=models.CharField(max_length=50),
        ),
    ]
